(function () {
  const translations = {
    "Home": "होम",
    "Mission": "मिशन",
    "Features": "फीचर्स",
    "Pricing": "प्राइसिंग",
    "Risk": "जोखिम",
    "Privacy": "प्राइवेसी",
    "Terms": "शर्तें",
    "Contact": "संपर्क",
    "Login": "लॉगिन",
    "English": "English",
    "Hindi": "हिंदी",
    "Intelligence Terminal": "इंटेलिजेंस टर्मिनल",
    "Market Intelligence Terminal": "मार्केट इंटेलिजेंस टर्मिनल",
    "MIT PRO Command Center": "MIT PRO कमांड सेंटर",
    "Understand The Market Before You Approach It": "बाजार के पास जाने से पहले उसे समझें",
    "Intelligence • Protection • Discipline": "इंटेलिजेंस • सुरक्षा • अनुशासन",
    "Desktop Intelligence Terminal": "डेस्कटॉप इंटेलिजेंस टर्मिनल",
    "MIT Pro combines Zeus Intelligence and Arjun Defense to help users understand market conditions with better awareness, discipline, and control.": "MIT Pro Zeus Intelligence और Arjun Defense को जोड़कर उपयोगकर्ताओं को अधिक जागरूकता, अनुशासन और नियंत्रण के साथ बाजार स्थितियों को समझने में मदद करता है।",
    "Zeus Analysis": "Zeus विश्लेषण",
    "Arjun Protection": "Arjun सुरक्षा",
    "Apex Core Running": "Apex Core सक्रिय",
    "Decision Support Only": "केवल निर्णय सहायता",
    "No Guaranteed Results": "किसी परिणाम की गारंटी नहीं",
    "Enter Terminal": "टर्मिनल देखें",
    "Request License": "लाइसेंस अनुरोध",
    "Read Risk Disclaimer": "जोखिम अस्वीकरण पढ़ें",
    "MIT PRO Features": "MIT PRO फीचर्स",
    "Powerful Intelligence. Human-Centered Protection.": "शक्तिशाली इंटेलिजेंस। मानव-केंद्रित सुरक्षा।",
    "MIT Pro is designed to help users better understand market behavior through adaptive intelligence, risk awareness, educational insights, and human-layer protection.": "MIT Pro अनुकूल इंटेलिजेंस, जोखिम जागरूकता, शैक्षिक जानकारी और मानव-स्तर सुरक्षा के माध्यम से उपयोगकर्ताओं को बाजार व्यवहार बेहतर समझने में मदद करने के लिए बनाया गया है।",
    "Zeus Intelligence": "Zeus इंटेलिजेंस",
    "Zeus Intelligence Core": "Zeus इंटेलिजेंस कोर",
    "Intelligence Active": "इंटेलिजेंस सक्रिय",
    "Neural Activity Active": "न्यूरल गतिविधि सक्रिय",
    "Analyzes market behavior, structure, momentum, volatility, liquidity, and confidence conditions in real time.": "वास्तविक समय में बाजार व्यवहार, संरचना, गति, अस्थिरता, लिक्विडिटी और कॉन्फिडेंस स्थितियों का विश्लेषण करता है।",
    "Arjun Defense": "Arjun डिफेंस",
    "Arjun Protection System": "Arjun सुरक्षा प्रणाली",
    "Protection Active": "सुरक्षा सक्रिय",
    "Protection Integrity 100%": "सुरक्षा अखंडता 100%",
    "Promotes discipline, awareness, session health, cooldown protection, and responsible decision-making.": "अनुशासन, जागरूकता, सेशन स्वास्थ्य, कूलडाउन सुरक्षा और जिम्मेदार निर्णय लेने को बढ़ावा देता है।",
    "MIT PRO Decision Support": "MIT PRO निर्णय सहायता",
    "Zeus AI Intelligence Engine": "Zeus AI इंटेलिजेंस इंजन",
    "Adaptive market analysis": "अनुकूल बाजार विश्लेषण",
    "Market state recognition": "बाजार स्थिति पहचान",
    "Confidence evaluation": "कॉन्फिडेंस मूल्यांकन",
    "Behavioral pattern recognition": "व्यवहार पैटर्न पहचान",
    "Volatility assessment": "अस्थिरता मूल्यांकन",
    "Liquidity monitoring": "लिक्विडिटी निगरानी",
    "Risk awareness monitoring": "जोखिम जागरूकता निगरानी",
    "Discipline protection": "अनुशासन सुरक्षा",
    "Emotional decision detection": "भावनात्मक निर्णय पहचान",
    "Session health monitoring": "सेशन स्वास्थ्य निगरानी",
    "Cooldown protection": "कूलडाउन सुरक्षा",
    "Behavioral alerts": "व्यवहार अलर्ट",
    "Live Intelligence Desk": "लाइव इंटेलिजेंस डेस्क",
    "Live market status": "लाइव बाजार स्थिति",
    "Market stability indicator": "बाजार स्थिरता संकेतक",
    "Confidence dashboard": "कॉन्फिडेंस डैशबोर्ड",
    "Risk assessment overview": "जोखिम मूल्यांकन अवलोकन",
    "Session intelligence feed": "सेशन इंटेलिजेंस फीड",
    "Adaptive intelligence updates": "अनुकूल इंटेलिजेंस अपडेट",
    "Liquidity Intelligence": "लिक्विडिटी इंटेलिजेंस",
    "Liquidity zone identification": "लिक्विडिटी ज़ोन पहचान",
    "Market pressure monitoring": "बाजार दबाव निगरानी",
    "Structure awareness": "संरचना जागरूकता",
    "Market balance analysis": "बाजार संतुलन विश्लेषण",
    "Dynamic liquidity mapping": "डायनामिक लिक्विडिटी मैपिंग",
    "Market State Detection": "बाजार स्थिति पहचान",
    "Stable environment": "स्थिर वातावरण",
    "Expansion phase": "विस्तार चरण",
    "Consolidation phase": "कंसोलिडेशन चरण",
    "Transitional phase": "ट्रांजिशन चरण",
    "Volatile conditions": "अस्थिर स्थितियां",
    "Uncertain environment": "अनिश्चित वातावरण",
    "Confidence Framework": "कॉन्फिडेंस फ्रेमवर्क",
    "Improved transparency": "बेहतर पारदर्शिता",
    "Additional context": "अतिरिक्त संदर्भ",
    "Enhanced awareness": "बेहतर जागरूकता",
    "Better decision support": "बेहतर निर्णय सहायता",
    "Confidence-based validation": "कॉन्फिडेंस आधारित वैलिडेशन",
    "Adaptive Intelligence": "अनुकूल इंटेलिजेंस",
    "Dynamic condition recognition": "डायनामिक स्थिति पहचान",
    "Behavioral adaptation": "व्यवहारिक अनुकूलन",
    "Context-aware analysis": "संदर्भ आधारित विश्लेषण",
    "Continuous intelligence evolution": "लगातार इंटेलिजेंस विकास",
    "Educational Intelligence": "शैक्षिक इंटेलिजेंस",
    "Contextual insights": "संदर्भ आधारित जानकारी",
    "Market behavior explanations": "बाजार व्यवहार की व्याख्या",
    "Risk awareness guidance": "जोखिम जागरूकता मार्गदर्शन",
    "Learning-oriented intelligence": "सीखने केंद्रित इंटेलिजेंस",
    "Decision context support": "निर्णय संदर्भ सहायता",
    "Security and Privacy": "सुरक्षा और प्राइवेसी",
    "Secure user authentication": "सुरक्षित उपयोगकर्ता प्रमाणीकरण",
    "License protection system": "लाइसेंस सुरक्षा प्रणाली",
    "Account security controls": "अकाउंट सुरक्षा नियंत्रण",
    "Privacy-focused design": "प्राइवेसी केंद्रित डिजाइन",
    "Secure platform access": "सुरक्षित प्लेटफॉर्म एक्सेस",
    "Why MIT PRO": "MIT PRO क्यों",
    "Adaptive intelligence": "अनुकूल इंटेलिजेंस",
    "Human-centered protection": "मानव-केंद्रित सुरक्षा",
    "Real-time market awareness": "रीयल-टाइम बाजार जागरूकता",
    "Educational insights": "शैक्षिक जानकारी",
    "Discipline-focused design": "अनुशासन केंद्रित डिजाइन",
    "Continuous innovation": "लगातार नवाचार",
    "Security and reliability": "सुरक्षा और विश्वसनीयता",
    "Liquidity Battlefield": "लिक्विडिटी बैटलफील्ड",
    "Liquidity Battlefield Engine": "लिक्विडिटी बैटलफील्ड इंजन",
    "A real product-inspired view of how MIT PRO explains zones, pressure, volatility, and session context inside the terminal.": "टर्मिनल के अंदर ज़ोन, दबाव, अस्थिरता और सेशन संदर्भ को MIT PRO कैसे समझाता है, इसका वास्तविक उत्पाद-प्रेरित दृश्य।",
    "MIT PRO Preview": "MIT PRO प्रीव्यू",
    "Market Story": "बाजार कहानी",
    "Observation Mode": "ऑब्जर्वेशन मोड",
    "Conditions are being mapped before validation.": "वैलिडेशन से पहले स्थितियों को मैप किया जा रहा है।",
    "Watched Zone": "निगरानी ज़ोन",
    "Timeframe Context": "टाइमफ्रेम संदर्भ",
    "Higher timeframe awareness is preferred.": "उच्च टाइमफ्रेम जागरूकता को प्राथमिकता दी जाती है।",
    "User State": "उपयोगकर्ता स्थिति",
    "Observe": "ऑब्जर्व",
    "Decision support remains educational.": "निर्णय सहायता शैक्षिक रहती है।",
    "Live Desk Preview": "लाइव डेस्क प्रीव्यू",
    "MIT PRO Live Desk Preview": "MIT PRO लाइव डेस्क प्रीव्यू",
    "The operating cockpit where Zeus readings, Arjun protection, timing awareness, and session discipline stay visible together.": "वह ऑपरेटिंग कॉकपिट जहां Zeus readings, Arjun सुरक्षा, टाइमिंग जागरूकता और सेशन अनुशासन साथ में दिखाई देते हैं।",
    "Market Reading": "बाजार रीडिंग",
    "Structure and pressure context stay visible.": "संरचना और दबाव संदर्भ दिखाई देता रहता है।",
    "Active Guard": "सक्रिय गार्ड",
    "Session discipline remains protected.": "सेशन अनुशासन सुरक्षित रहता है।",
    "Tactical Intelligence": "टैक्टिकल इंटेलिजेंस",
    "Command Access Levels": "कमांड एक्सेस स्तर",
    "Guardian, Commander, Supreme": "Guardian, Commander, Supreme",
    "Access levels stay consistent from the command-center entrance to the license activation chamber.": "एक्सेस स्तर कमांड सेंटर प्रवेश से लाइसेंस एक्टिवेशन तक एक जैसे रहते हैं।",
    "Foundation command": "फाउंडेशन कमांड",
    "Guardian Access": "Guardian एक्सेस",
    "For learning, awareness, and basic protection.": "सीखने, जागरूकता और बेसिक सुरक्षा के लिए।",
    "REAL mode": "REAL मोड",
    "Core strategies": "कोर रणनीतियां",
    "Basic guard": "बेसिक गार्ड",
    "View Guardian": "Guardian देखें",
    "Most Popular": "सबसे लोकप्रिय",
    "Commander Access": "Commander एक्सेस",
    "Complete MIT Pro experience for active users.": "सक्रिय उपयोगकर्ताओं के लिए पूरा MIT Pro अनुभव।",
    "Advanced tools": "एडवांस टूल्स",
    "Timing sync": "टाइमिंग सिंक",
    "Full discipline guard": "पूर्ण अनुशासन गार्ड",
    "View Commander": "Commander देखें",
    "Full command": "पूर्ण कमांड",
    "Supreme Access": "Supreme एक्सेस",
    "Full command center access and advanced coverage.": "पूर्ण कमांड सेंटर एक्सेस और एडवांस कवरेज।",
    "Advanced OTC suite": "एडवांस OTC सूट",
    "Full battlefield": "पूर्ण बैटलफील्ड",
    "Future priority access": "भविष्य प्राथमिकता एक्सेस",
    "View Supreme": "Supreme देखें",
    "MIT PRO Mission": "MIT PRO मिशन",
    "Knowledge Before Action. Protection Before Emotion.": "कार्रवाई से पहले ज्ञान। भावना से पहले सुरक्षा।",
    "At MIT PRO, Market Intelligence Terminal, our mission is to help individuals make smarter, calmer, and more informed decisions by transforming complex market behavior into understandable intelligence.": "MIT PRO, Market Intelligence Terminal में हमारा मिशन जटिल बाजार व्यवहार को समझने योग्य इंटेलिजेंस में बदलकर लोगों को अधिक समझदार, शांत और जागरूक निर्णय लेने में मदद करना है।",
    "Our Mission": "हमारा मिशन",
    "Adaptive intelligence built for awareness, not impulse.": "जागरूकता के लिए बनी अनुकूल इंटेलिजेंस, आवेग के लिए नहीं।",
    "The MIT PRO Promise": "MIT PRO वादा",
    "We do not promise outcomes.": "हम परिणामों का वादा नहीं करते।",
    "We do not promote shortcuts.": "हम शॉर्टकट को बढ़ावा नहीं देते।",
    "We do not encourage blind decisions.": "हम अंधे निर्णयों को प्रोत्साहित नहीं करते।",
    "Understand": "समझें",
    "Market behavior translated into clear intelligence.": "बाजार व्यवहार को स्पष्ट इंटेलिजेंस में बदला गया।",
    "Recognize Risk": "जोखिम पहचानें",
    "Conditions, pressure, and uncertainty shown before action.": "कार्रवाई से पहले स्थितियां, दबाव और अनिश्चितता दिखाई जाती है।",
    "Stay Disciplined": "अनुशासित रहें",
    "A focused workspace designed for calmer decisions.": "शांत निर्णयों के लिए बनाया गया केंद्रित वर्कस्पेस।",
    "Why We Exist": "हम क्यों हैं",
    "Protection First": "सुरक्षा पहले",
    "Education Over Emotion": "भावना से पहले शिक्षा",
    "Human Intelligence + AI": "मानव इंटेलिजेंस + AI",
    "Transparency and Responsibility": "पारदर्शिता और जिम्मेदारी",
    "Continuous Improvement": "लगातार सुधार",
    "Our Vision": "हमारा विजन",
    "Commitment": "प्रतिबद्धता",
    "User Awareness First": "उपयोगकर्ता जागरूकता पहले",
    "Discipline Before Action": "कार्रवाई से पहले अनुशासन",
    "Protection Before Exposure": "एक्सपोजर से पहले सुरक्षा",
    "Intelligence Before Decision": "निर्णय से पहले इंटेलिजेंस",
    "MIT PRO License Access": "MIT PRO लाइसेंस एक्सेस",
    "MIT Pro Partner Portal": "MIT Pro पार्टनर पोर्टल",
    "AI sales intelligence, referral follow-up, and license care": "AI sales intelligence, referral follow-up और license care",
    "Protected partner access": "सुरक्षित पार्टनर एक्सेस",
    "Sales Workspace": "सेल्स वर्कस्पेस",
    "Sign in to review referrals, customer follow-up, and license expiry without opening trading controls.": "ट्रेडिंग कंट्रोल खोले बिना referrals, customer follow-up और license expiry देखने के लिए साइन इन करें।",
    "Unlock Partner Portal": "पार्टनर पोर्टल अनलॉक करें",
    "Open Terminal": "टर्मिनल खोलें",
    "Logout": "लॉगआउट",
    "Activate Your MIT PRO Access": "अपना MIT PRO एक्सेस एक्टिव करें",
    "Start with the license level that matches your market coverage, protection needs, and discipline workflow. Manual USDT confirmation is active until Stripe payment is available.": "अपने बाजार कवरेज, सुरक्षा जरूरतों और अनुशासन वर्कफ्लो के अनुसार लाइसेंस स्तर से शुरू करें। Stripe उपलब्ध होने तक मैनुअल USDT पुष्टि सक्रिय है।",
    "Compare Plans": "प्लान तुलना करें",
    "Payment Safety": "पेमेंट सुरक्षा",
    "MIT PRO will never ask for your wallet seed phrase, private key, remote wallet access, or exchange login. Send payment only after confirming the official wallet details with MIT PRO support.": "MIT PRO कभी भी आपका wallet seed phrase, private key, remote wallet access या exchange login नहीं मांगेगा। आधिकारिक wallet details MIT PRO support से पुष्टि करने के बाद ही payment भेजें।",
    "Never Share": "कभी साझा न करें",
    "Seed Phrase": "Seed Phrase",
    "Private Key": "Private Key",
    "Remote Access": "Remote Access",
    "Exchange Password": "Exchange Password",
    "OTP Codes": "OTP Codes",
    "Screen Sharing Requests": "Screen Sharing Requests",
    "Risk Disclaimer": "जोखिम अस्वीकरण",
    "Protection First": "सुरक्षा पहले",
    "Trading Risk": "ट्रेडिंग जोखिम",
    "No Financial Advice": "कोई वित्तीय सलाह नहीं",
    "No Profit Guarantee": "लाभ की कोई गारंटी नहीं",
    "No Trade Execution": "कोई ट्रेड निष्पादन नहीं",
    "Not a Broker or Adviser": "ब्रोकर या सलाहकार नहीं",
    "Market Uncertainty": "बाजार अनिश्चितता",
    "High-Risk Instruments": "उच्च जोखिम उपकरण",
    "User Responsibility": "उपयोगकर्ता जिम्मेदारी",
    "Past Performance": "पिछला प्रदर्शन",
    "No Liability": "कोई दायित्व नहीं",
    "Privacy Policy": "प्राइवेसी पॉलिसी",
    "Terms of Use": "उपयोग की शर्तें",
    "Contact MIT PRO": "MIT PRO से संपर्क करें",
    "MIT PRO Support Channel": "MIT PRO सपोर्ट चैनल",
    "Support Desk": "सपोर्ट डेस्क",
    "MIT PRO Support Gateway": "MIT PRO सपोर्ट गेटवे",
    "Send Request": "अनुरोध भेजें",
    "Support Request": "सपोर्ट अनुरोध",
    "Your name": "आपका नाम",
    "Your email": "आपका ईमेल",
    "Subject": "विषय",
    "Message": "संदेश",
    "Send Support Request": "सपोर्ट अनुरोध भेजें",
    "Human Review": "मानव समीक्षा",
    "License Support": "लाइसेंस सपोर्ट",
    "Intelligence &bull; Protection &bull; Discipline": "इंटेलिजेंस &bull; सुरक्षा &bull; अनुशासन",
    "MIT PRO CORE REACTOR": "MIT PRO कोर रिएक्टर",
    "COMMAND CENTER": "कमांड सेंटर",
    "ACCESS COMMAND CENTER": "एक्सेस कमांड सेंटर",
    "Awareness Engine": "जागरूकता इंजन",
    "Market Context": "बाजार संदर्भ",
    "Protection System": "सुरक्षा प्रणाली",
    "Session Discipline": "सेशन अनुशासन",
    "Terminal Access": "टर्मिनल एक्सेस",
    "License Gateway": "लाइसेंस गेटवे",
    "Recommended Access": "अनुशंसित एक्सेस",
    "Foundation Access": "फाउंडेशन एक्सेस",
    "Full Access": "पूर्ण एक्सेस",
    "License Activation Chamber": "लाइसेंस एक्टिवेशन चेंबर",
    "Request": "अनुरोध",
    "User details received": "उपयोगकर्ता विवरण प्राप्त",
    "Verify": "सत्यापन",
    "Manual review active": "मैनुअल समीक्षा सक्रिय",
    "Arjun Security Check": "Arjun सुरक्षा जांच",
    "License profile protected": "लाइसेंस प्रोफाइल सुरक्षित",
    "License Ready": "लाइसेंस तैयार",
    "Access code issued after validation": "वैलिडेशन के बाद एक्सेस कोड जारी",
    "License Activation": "लाइसेंस एक्टिवेशन",
    "Users move from the command center into a focused license request flow with manual USDT verification, admin review, and support visibility.": "उपयोगकर्ता कमांड सेंटर से मैनुअल USDT सत्यापन, एडमिन समीक्षा और सपोर्ट विजिबिलिटी वाले केंद्रित लाइसेंस अनुरोध प्रवाह में जाते हैं।",
    "Open License Activation": "लाइसेंस एक्टिवेशन खोलें",
    "Contact MIT PRO Team": "MIT PRO टीम से संपर्क करें",
    "MIT PRO was created to become a layer of protection, education, and awareness in a world where many people are influenced by noise, misinformation, emotional reactions, unrealistic promises, and manipulation.": "MIT PRO को ऐसी दुनिया में सुरक्षा, शिक्षा और जागरूकता की परत बनने के लिए बनाया गया है जहां कई लोग शोर, गलत जानकारी, भावनात्मक प्रतिक्रियाओं, अवास्तविक वादों और हेरफेर से प्रभावित होते हैं।",
    "We believe that knowledge should come before action, discipline should come before emotion, and understanding should come before decision-making.": "हम मानते हैं कि कार्रवाई से पहले ज्ञान, भावना से पहले अनुशासन, और निर्णय लेने से पहले समझ होनी चाहिए।",
    "MIT PRO is not built to encourage impulsive behavior. It is built to help users understand what is happening, why it is happening, and when caution may be more important than action.": "MIT PRO आवेगपूर्ण व्यवहार को बढ़ावा देने के लिए नहीं बनाया गया है। यह उपयोगकर्ताओं को यह समझने में मदद करने के लिए बनाया गया है कि क्या हो रहा है, क्यों हो रहा है, और कब कार्रवाई से अधिक सावधानी महत्वपूर्ण हो सकती है।",
    "We promise to continuously build technology that helps users learn more, understand more, protect more, think better, and decide smarter.": "हम लगातार ऐसी तकनीक बनाने का वादा करते हैं जो उपयोगकर्ताओं को अधिक सीखने, अधिक समझने, अधिक सुरक्षित रहने, बेहतर सोचने और अधिक समझदारी से निर्णय लेने में मदद करे।",
    "Every day, people act under emotional pressure, chase recovery after losses, follow unverified information, fall victim to misleading promises, and make decisions without understanding market conditions.": "हर दिन लोग भावनात्मक दबाव में काम करते हैं, नुकसान के बाद रिकवरी का पीछा करते हैं, अप्रमाणित जानकारी का पालन करते हैं, भ्रामक वादों का शिकार होते हैं, और बाजार स्थितियों को समझे बिना निर्णय लेते हैं।",
    "The first responsibility of intelligence is protection. Before looking for opportunities, users should understand risk, instability, uncertainty, and changing conditions.": "इंटेलिजेंस की पहली जिम्मेदारी सुरक्षा है। अवसर देखने से पहले उपयोगकर्ताओं को जोखिम, अस्थिरता, अनिश्चितता और बदलती स्थितियों को समझना चाहिए।",
    "Long-term improvement comes from learning and understanding, not emotional reaction or short-term excitement. Every interaction should increase awareness.": "लंबी अवधि का सुधार सीखने और समझने से आता है, भावनात्मक प्रतिक्रिया या अल्पकालिक उत्साह से नहीं। हर इंटरैक्शन जागरूकता बढ़ाना चाहिए।",
    "Technology should support human judgment, not replace it. MIT PRO combines adaptive intelligence systems with human validation so users remain in control.": "तकनीक को मानव निर्णय का समर्थन करना चाहिए, उसे बदलना नहीं चाहिए। MIT PRO अनुकूल इंटेलिजेंस सिस्टम को मानव वैलिडेशन के साथ जोड़ता है ताकि उपयोगकर्ता नियंत्रण में रहें।",
    "Users deserve clarity. MIT PRO explains conditions, confidence levels, risks, and reasoning in a way that promotes understanding rather than blind reliance.": "उपयोगकर्ता स्पष्टता के पात्र हैं। MIT PRO स्थितियों, कॉन्फिडेंस स्तरों, जोखिमों और कारणों को ऐसे तरीके से समझाता है जो अंधे भरोसे के बजाय समझ को बढ़ावा देता है।",
    "Markets, technology, and user behavior evolve. MIT PRO is committed to improving intelligence, protection mechanisms, education, and user experience.": "बाजार, तकनीक और उपयोगकर्ता व्यवहार विकसित होते रहते हैं। MIT PRO इंटेलिजेंस, सुरक्षा तंत्र, शिक्षा और उपयोगकर्ता अनुभव को लगातार बेहतर करने के लिए प्रतिबद्ध है।",
    "To become the world's most trusted Market Intelligence Terminal, empowering individuals through education, awareness, adaptive intelligence, and human-centered protection.": "दुनिया का सबसे भरोसेमंद Market Intelligence Terminal बनना, जो शिक्षा, जागरूकता, अनुकूल इंटेलिजेंस और मानव-केंद्रित सुरक्षा के माध्यम से लोगों को सशक्त करे।",
    "\"Knowledge Before Action. Protection Before Emotion. Understanding Before Every Decision.\"": "\"कार्रवाई से पहले ज्ञान। भावना से पहले सुरक्षा। हर निर्णय से पहले समझ।\"",
    "Stripe Coming Soon": "Stripe जल्द आ रहा है",
    "License Issued After Verification": "सत्यापन के बाद लाइसेंस जारी",
    "Zeus Mind": "Zeus माइंड",
    "Continuously interprets market structure, liquidity behavior, timing context, and evolving market conditions to assist user awareness.": "उपयोगकर्ता जागरूकता में सहायता के लिए बाजार संरचना, लिक्विडिटी व्यवहार, टाइमिंग संदर्भ और बदलती बाजार स्थितियों की लगातार व्याख्या करता है।",
    "Arjun Defense System": "Arjun डिफेंस सिस्टम",
    "Designed to promote discipline through session controls, cooldown protection, behavioral safeguards, and capital preservation tools.": "सेशन कंट्रोल, कूलडाउन सुरक्षा, व्यवहारिक सुरक्षा और पूंजी संरक्षण टूल्स के माध्यम से अनुशासन को बढ़ावा देने के लिए डिजाइन किया गया है।",
    "Starter protection": "स्टार्टर सुरक्षा",
    "For learning, awareness, and foundation protection.": "सीखने, जागरूकता और फाउंडेशन सुरक्षा के लिए।",
    "Foundation Arjun guard": "फाउंडेशन Arjun गार्ड",
    "Choose Guardian": "Guardian चुनें",
    "REAL advanced tools": "REAL एडवांस टूल्स",
    "OTC core access": "OTC कोर एक्सेस",
    "Full Arjun discipline guard": "पूर्ण Arjun अनुशासन गार्ड",
    "Choose Commander": "Commander चुनें",
    "Advanced OTC intelligence": "एडवांस OTC इंटेलिजेंस",
    "Full Battlefield suite": "पूर्ण Battlefield सूट",
    "Choose Supreme": "Supreme चुनें",
    "Feature Comparison": "फीचर तुलना",
    "Feature": "फीचर",
    "Guardian": "Guardian",
    "Commander": "Commander",
    "Supreme": "Supreme",
    "Intelligence": "इंटेलिजेंस",
    "Zeus Market Intelligence": "Zeus बाजार इंटेलिजेंस",
    "Core": "कोर",
    "Advanced": "एडवांस",
    "Foundation": "फाउंडेशन",
    "REAL market mode": "REAL बाजार मोड",
    "OTC market access": "OTC बाजार एक्सेस",
    "Partial": "आंशिक",
    "Advanced REAL strategies": "एडवांस REAL रणनीतियां",
    "OTC trap suite": "OTC ट्रैप सूट",
    "Core only": "केवल कोर",
    "Learning cards": "लर्निंग कार्ड",
    "Timing Sync Center": "टाइमिंग सिंक सेंटर",
    "Arjun capital guard": "Arjun कैपिटल गार्ड",
    "Arjun discipline guard": "Arjun अनुशासन गार्ड",
    "Session Intelligence Audit": "सेशन इंटेलिजेंस ऑडिट",
    "Performance Mode": "परफॉर्मेंस मोड",
    "Zeus Evolution": "Zeus इवोल्यूशन",
    "Zeus Evolution Engine": "Zeus इवोल्यूशन इंजन",
    "Phase II": "फेज II",
    "Phase III": "फेज III",
    "Future Core": "भविष्य कोर",
    "Request Purchase": "खरीद अनुरोध",
    "Waiting for user details": "उपयोगकर्ता विवरण की प्रतीक्षा",
    "Secure Verification": "सुरक्षित सत्यापन",
    "Arjun Protected": "Arjun सुरक्षित",
    "Select Plan": "प्लान चुनें",
    "Send Request": "अनुरोध भेजें",
    "Confirm USDT": "USDT पुष्टि करें",
    "Receive License": "लाइसेंस प्राप्त करें",
    "User": "उपयोगकर्ता",
    "Mail": "मेल",
    "Access": "एक्सेस",
    "Network": "नेटवर्क",
    "TXID": "TXID",
    "Payment Screenshot Optional": "पेमेंट स्क्रीनशॉट वैकल्पिक",
    "Attach USDT payment proof only if payment is already completed. PNG, JPG, WEBP, or PDF up to 5 MB.": "USDT पेमेंट प्रूफ केवल तभी संलग्न करें जब पेमेंट पूरा हो चुका हो। PNG, JPG, WEBP या PDF, अधिकतम 5 MB।",
    "Submit USDT Purchase Request": "USDT खरीद अनुरोध भेजें",
    "Manual USDT confirmation": "मैनुअल USDT पुष्टि",
    "Payment details are verified before any license code is issued.": "किसी भी लाइसेंस कोड के जारी होने से पहले पेमेंट विवरण सत्यापित किए जाते हैं।",
    "Stripe will be added later. Current public purchase flow is USDT manual confirmation only.": "Stripe बाद में जोड़ा जाएगा। वर्तमान सार्वजनिक खरीद प्रवाह केवल USDT मैनुअल पुष्टि है।",
    "Phone / WhatsApp": "फोन / WhatsApp",
    "Payment reference optional": "पेमेंट रेफरेंस वैकल्पिक",
    "Optional message. Example: I want Commander Access and will pay through USDT TRC20.": "वैकल्पिक संदेश। उदाहरण: मुझे Commander Access चाहिए और मैं USDT TRC20 से भुगतान करूंगा।",
    "MIT PRO is an educational, informational, observation, market-intelligence, trader-protection, and decision-support platform. It is not financial advice, not a broker, not an investment adviser, and not an outcome-assurance service.": "MIT PRO एक शैक्षिक, सूचनात्मक, ऑब्जर्वेशन, मार्केट-इंटेलिजेंस, ट्रेडर-प्रोटेक्शन और निर्णय-सहायता प्लेटफॉर्म है। यह वित्तीय सलाह नहीं है, ब्रोकर नहीं है, निवेश सलाहकार नहीं है, और परिणाम-आश्वासन सेवा नहीं है।",
    "Trading and market participation involve risk. Users may lose some or all of their funds. Users should not trade money they cannot afford to lose.": "ट्रेडिंग और बाजार भागीदारी में जोखिम शामिल है। उपयोगकर्ता अपनी कुछ या पूरी राशि खो सकते हैं। उपयोगकर्ताओं को ऐसा पैसा ट्रेड नहीं करना चाहिए जिसे खोना वे वहन नहीं कर सकते।",
    "MIT PRO does not provide financial, investment, legal, tax, brokerage, or professional trading advice. Information shown by MIT PRO is for educational, informational, observation, and decision-support purposes only.": "MIT PRO वित्तीय, निवेश, कानूनी, टैक्स, ब्रोकरेज या प्रोफेशनल ट्रेडिंग सलाह प्रदान नहीं करता। MIT PRO द्वारा दिखाई गई जानकारी केवल शिक्षा, सूचना, ऑब्जर्वेशन और निर्णय-सहायता के उद्देश्य से है।",
    "MIT PRO does not guarantee profits, income, trading accuracy, successful outcomes, or loss prevention. Any market analysis, alerts, confidence levels, examples, screenshots, demos, or historical references do not guarantee future results.": "MIT PRO लाभ, आय, ट्रेडिंग सटीकता, सफल परिणाम या नुकसान रोकने की गारंटी नहीं देता। कोई भी बाजार विश्लेषण, अलर्ट, कॉन्फिडेंस स्तर, उदाहरण, स्क्रीनशॉट, डेमो या ऐतिहासिक संदर्भ भविष्य के परिणामों की गारंटी नहीं देते।",
    "MIT PRO does not place trades, execute orders, manage funds, control brokerage accounts, or make final trading decisions for users. Every decision remains the sole responsibility of the user.": "MIT PRO उपयोगकर्ताओं के लिए ट्रेड नहीं लगाता, ऑर्डर निष्पादित नहीं करता, फंड प्रबंधित नहीं करता, ब्रोकरेज अकाउंट नियंत्रित नहीं करता, या अंतिम ट्रेडिंग निर्णय नहीं लेता। हर निर्णय उपयोगकर्ता की अपनी जिम्मेदारी है।",
    "MIT PRO is not a broker, exchange, financial institution, investment adviser, fund manager, portfolio manager, managed trading service, or copy-trading service.": "MIT PRO ब्रोकर, एक्सचेंज, वित्तीय संस्था, निवेश सलाहकार, फंड मैनेजर, पोर्टफोलियो मैनेजर, managed trading service या copy-trading service नहीं है।",
    "Market conditions can change quickly. Any analysis, AI output, intelligence health indicator, confidence score, market state reading, timing indicator, risk warning, or protection alert may be delayed, incomplete, inaccurate, or affected by data, timing, platform, technical, or market limitations.": "बाजार स्थितियां तेजी से बदल सकती हैं। कोई भी विश्लेषण, AI output, intelligence health indicator, confidence score, market state reading, timing indicator, risk warning या protection alert data, timing, platform, technical या market limitations के कारण delayed, incomplete, inaccurate या प्रभावित हो सकता है।",
    "Forex, OTC markets, crypto, derivatives, binary-style products, leveraged instruments, and other speculative markets may carry high risk and may not be suitable for all users.": "Forex, OTC markets, crypto, derivatives, binary-style products, leveraged instruments और अन्य speculative markets उच्च जोखिम वाले हो सकते हैं और सभी उपयोगकर्ताओं के लिए उपयुक्त नहीं हो सकते।",
    "Users are responsible for understanding the risks, complying with local laws, following broker/platform rules, and making their own independent decisions. Users must independently verify all information before acting.": "उपयोगकर्ता जोखिमों को समझने, स्थानीय कानूनों का पालन करने, broker/platform rules का पालन करने और अपने स्वतंत्र निर्णय लेने के लिए जिम्मेदार हैं। कार्रवाई से पहले उपयोगकर्ताओं को सभी जानकारी स्वतंत्र रूप से सत्यापित करनी चाहिए।",
    "Past performance, demo results, backtests, examples, user feedback, screenshots, or testimonials do not guarantee future results.": "पिछला प्रदर्शन, demo results, backtests, examples, user feedback, screenshots या testimonials भविष्य के परिणामों की गारंटी नहीं देते।",
    "To the maximum extent permitted by applicable law, MIT PRO and its team are not liable for trading losses, missed opportunities, platform issues, user decisions, broker issues, market volatility, technical delays, data errors, or misuse of the platform.": "लागू कानून द्वारा अनुमत अधिकतम सीमा तक, MIT PRO और उसकी टीम trading losses, missed opportunities, platform issues, user decisions, broker issues, market volatility, technical delays, data errors या platform misuse के लिए जिम्मेदार नहीं हैं।",
    "For questions, contact": "प्रश्नों के लिए संपर्क करें",
    "MIT PRO Data Protection": "MIT PRO डेटा सुरक्षा",
    "This Privacy Policy explains how MIT PRO may collect, use, store, protect, and process user information.": "यह Privacy Policy बताती है कि MIT PRO उपयोगकर्ता जानकारी को कैसे collect, use, store, protect और process कर सकता है।",
    "License Security": "लाइसेंस सुरक्षा",
    "No Data Sale": "डेटा बिक्री नहीं",
    "Support Access": "सपोर्ट एक्सेस",
    "Data We May Collect": "हम कौन सा डेटा collect कर सकते हैं",
    "MIT PRO may collect name, email address, account information, license information, device identifiers, login/session information, usage activity, app performance logs, error/crash reports, support messages, payment-related references if applicable, technical diagnostics, IP address and browser/device information, and cookies or analytics data if used.": "MIT PRO नाम, ईमेल पता, अकाउंट जानकारी, लाइसेंस जानकारी, device identifiers, login/session information, usage activity, app performance logs, error/crash reports, support messages, payment-related references, technical diagnostics, IP address, browser/device information, और cookies या analytics data collect कर सकता है यदि उपयोग किया जाए।",
    "Why We Collect Data": "हम डेटा क्यों collect करते हैं",
    "Data may be used to create and manage accounts, provide license access, secure the platform, prevent misuse and unauthorized access, provide support, improve performance, monitor crashes/errors, improve user experience, detect abuse, fraud, or license violations, and comply with legal obligations.": "डेटा accounts बनाने और manage करने, license access देने, platform secure करने, misuse और unauthorized access रोकने, support देने, performance सुधारने, crashes/errors monitor करने, user experience सुधारने, abuse, fraud या license violations detect करने, और legal obligations पूरा करने के लिए उपयोग हो सकता है।",
    "Cookies and Analytics": "Cookies और Analytics",
    "If cookies or analytics are used, they may help understand website usage, improve performance, secure sessions, and improve the platform.": "यदि cookies या analytics उपयोग किए जाते हैं, तो वे website usage समझने, performance सुधारने, sessions secure करने और platform सुधारने में मदद कर सकते हैं।",
    "Third-Party Providers": "Third-Party Providers",
    "MIT PRO may use third-party providers for hosting, domain/DNS, email, payment processing, analytics, licensing, customer support, security, and error tracking. These third-party services may process data according to their own policies.": "MIT PRO hosting, domain/DNS, email, payment processing, analytics, licensing, customer support, security और error tracking के लिए third-party providers का उपयोग कर सकता है। ये services अपनी policies के अनुसार data process कर सकती हैं।",
    "Data Security": "डेटा सुरक्षा",
    "MIT PRO uses reasonable technical and organizational measures to protect user data. However, no system can be guaranteed completely secure.": "MIT PRO user data की सुरक्षा के लिए reasonable technical और organizational measures उपयोग करता है। हालांकि, कोई भी system पूरी तरह secure होने की गारंटी नहीं दे सकता।",
    "Data Retention": "डेटा retention",
    "MIT PRO may retain data as long as necessary to operate the platform, provide support, meet legal obligations, resolve disputes, prevent misuse, and enforce agreements.": "MIT PRO platform operate करने, support देने, legal obligations पूरा करने, disputes resolve करने, misuse रोकने और agreements enforce करने के लिए जितनी देर जरूरी हो data retain कर सकता है।",
    "User Rights": "उपयोगकर्ता अधिकार",
    "Depending on applicable law, users may request access, correction, deletion, or review of their personal data by contacting": "लागू कानून के अनुसार, उपयोगकर्ता अपने personal data के access, correction, deletion या review का अनुरोध संपर्क करके कर सकते हैं",
    "User Compliance": "उपयोगकर्ता compliance",
    "Users are responsible for ensuring their use of MIT PRO complies with applicable rules, platform requirements, and privacy obligations relevant to them.": "उपयोगकर्ता यह सुनिश्चित करने के लिए जिम्मेदार हैं कि MIT PRO का उनका उपयोग लागू नियमों, platform requirements और privacy obligations के अनुरूप हो।",
    "No Sale of Personal Information": "Personal information की बिक्री नहीं",
    "MIT PRO does not sell personal information. Information is used for legitimate platform, support, security, licensing, and compliance purposes.": "MIT PRO personal information नहीं बेचता। जानकारी legitimate platform, support, security, licensing और compliance purposes के लिए उपयोग होती है।",
    "For privacy questions, contact": "Privacy प्रश्नों के लिए संपर्क करें",
    "MIT PRO Access Rules": "MIT PRO एक्सेस नियम",
    "By accessing or using MIT PRO, the user agrees to these Terms of Use.": "MIT PRO को access या use करके, उपयोगकर्ता इन Terms of Use से सहमत होता है।",
    "License Boundaries": "लाइसेंस सीमाएं",
    "Acceptable Use": "स्वीकार्य उपयोग",
    "Platform Purpose": "प्लेटफॉर्म उद्देश्य",
    "MIT PRO is provided for educational, informational, observation, market-intelligence, trader-protection, and decision-support purposes only.": "MIT PRO केवल education, information, observation, market-intelligence, trader-protection और decision-support purposes के लिए प्रदान किया जाता है।",
    "MIT PRO does not provide financial, investment, legal, tax, brokerage, or trading advice.": "MIT PRO financial, investment, legal, tax, brokerage या trading advice प्रदान नहीं करता।",
    "No Guarantee": "कोई गारंटी नहीं",
    "MIT PRO does not guarantee profits, accuracy, availability, results, or loss prevention.": "MIT PRO profits, accuracy, availability, results या loss prevention की गारंटी नहीं देता।",
    "Users are solely responsible for their own trading decisions, account actions, risk management, compliance with laws, and use of any broker or trading platform.": "उपयोगकर्ता अपने trading decisions, account actions, risk management, laws compliance, और किसी भी broker या trading platform के use के लिए पूरी तरह जिम्मेदार हैं।",
    "Eligibility and Compliance": "Eligibility और compliance",
    "Users must comply with all applicable laws, regulations, broker/platform rules, and age or eligibility requirements in their location.": "उपयोगकर्ताओं को अपने location में सभी applicable laws, regulations, broker/platform rules और age या eligibility requirements का पालन करना होगा।",
    "Account and License Responsibility": "Account और license responsibility",
    "Users must keep login details secure.": "उपयोगकर्ताओं को login details सुरक्षित रखनी चाहिए।",
    "License access is personal unless written permission is given.": "लाइसेंस एक्सेस personal है जब तक written permission न दी जाए।",
    "Sharing, selling, renting, or transferring access is not allowed.": "Access share, sell, rent या transfer करना allowed नहीं है।",
    "Device binding or access controls may be used.": "Device binding या access controls उपयोग किए जा सकते हैं।",
    "Prohibited Use": "प्रतिबंधित उपयोग",
    "Users must not use MIT PRO for scams or misleading promotions; market MIT PRO as a guaranteed outcome service; impersonate MIT PRO; resell access without permission; mislead users with fake results or screenshots; use MIT PRO for unauthorized financial advisory activity; violate broker/platform rules; attempt to bypass licensing or security controls; reverse engineer, copy, modify, redistribute, or tamper with the platform; or use MIT PRO for illegal, abusive, fraudulent, or harmful activity.": "उपयोगकर्ता MIT PRO का उपयोग scams या misleading promotions के लिए नहीं कर सकते; MIT PRO को guaranteed outcome service के रूप में market नहीं कर सकते; MIT PRO की impersonation नहीं कर सकते; permission के बिना access resell नहीं कर सकते; fake results या screenshots से users को mislead नहीं कर सकते; unauthorized financial advisory activity के लिए MIT PRO का उपयोग नहीं कर सकते; broker/platform rules violate नहीं कर सकते; licensing या security controls bypass करने की कोशिश नहीं कर सकते; platform को reverse engineer, copy, modify, redistribute या tamper नहीं कर सकते; या illegal, abusive, fraudulent या harmful activity के लिए MIT PRO का उपयोग नहीं कर सकते।",
    "AI and Technical Limitations": "AI और technical limitations",
    "MIT PRO may use AI, automation, image analysis, timing interpretation, market-state logic, and protection rules. AI outputs, market-state readings, confidence scores, timing indicators, trap warnings, and protection alerts may be delayed, incomplete, inaccurate, or unavailable. Users must independently verify all information.": "MIT PRO AI, automation, image analysis, timing interpretation, market-state logic और protection rules का उपयोग कर सकता है। AI outputs, market-state readings, confidence scores, timing indicators, trap warnings और protection alerts delayed, incomplete, inaccurate या unavailable हो सकते हैं। उपयोगकर्ताओं को सभी जानकारी independently verify करनी चाहिए।",
    "Service Availability": "Service availability",
    "MIT PRO may be updated, interrupted, changed, limited, or discontinued. Continuous availability is not guaranteed.": "MIT PRO update, interrupt, change, limit या discontinue किया जा सकता है। Continuous availability की गारंटी नहीं है।",
    "Suspension and Termination": "Suspension और termination",
    "MIT PRO may suspend or terminate access for misuse, fraud, abuse, unauthorized resale, license violations, security issues, or breach of these terms.": "MIT PRO misuse, fraud, abuse, unauthorized resale, license violations, security issues या इन terms के breach पर access suspend या terminate कर सकता है।",
    "Intellectual Property": "Intellectual property",
    "All MIT PRO branding, design, content, software, logic, names, visuals, and materials are owned by MIT PRO or its licensors. Users may not copy, reproduce, or redistribute without permission.": "MIT PRO branding, design, content, software, logic, names, visuals और materials MIT PRO या उसके licensors के स्वामित्व में हैं। उपयोगकर्ता permission के बिना copy, reproduce या redistribute नहीं कर सकते।",
    "Promotion and Acceptable Use": "Promotion और acceptable use",
    "Promoters, users, affiliates, or team members must not market MIT PRO using outcome-assurance claims, misleading income screenshots, fake testimonials, unauthorized pricing, or claims that MIT PRO provides financial advice. Any misuse may result in suspension or termination.": "Promoters, users, affiliates या team members outcome-assurance claims, misleading income screenshots, fake testimonials, unauthorized pricing, या MIT PRO financial advice देता है ऐसे claims से MIT PRO को market नहीं कर सकते। Misuse पर suspension या termination हो सकता है।",
    "Limitation of Liability": "Liability limitation",
    "To the maximum extent permitted by law, MIT PRO and its team are not liable for trading losses, loss of profits, indirect damages, technical issues, user decisions, broker actions, data errors, delays, or misuse.": "कानून द्वारा अनुमत अधिकतम सीमा तक, MIT PRO और उसकी टीम trading losses, loss of profits, indirect damages, technical issues, user decisions, broker actions, data errors, delays या misuse के लिए liable नहीं हैं।",
    "Indemnification": "Indemnification",
    "Users agree to protect MIT PRO and its team from claims, damages, losses, or expenses arising from misuse, violation of terms, illegal activity, misleading promotion, or user trading decisions.": "उपयोगकर्ता misuse, terms violation, illegal activity, misleading promotion या user trading decisions से उत्पन्न claims, damages, losses या expenses से MIT PRO और उसकी team को protect करने से सहमत हैं।",
    "Changes to Terms": "Terms में बदलाव",
    "MIT PRO may update these Terms of Use from time to time. Continued use means acceptance of updated terms.": "MIT PRO समय-समय पर इन Terms of Use को update कर सकता है। Continued use का अर्थ updated terms की acceptance है।",
    "For support, licensing, account, or legal questions, contact": "Support, licensing, account या legal questions के लिए संपर्क करें",
    "For licensing, account access, technical support, privacy questions, legal inquiries, demo access, or general support, send a secure request to the MIT PRO team.": "Licensing, account access, technical support, privacy questions, legal inquiries, demo access या general support के लिए MIT PRO team को secure request भेजें।",
    "Use this channel for platform support, account help, license questions, payment proof follow-up, and legal/privacy requests.": "इस channel का उपयोग platform support, account help, license questions, payment proof follow-up और legal/privacy requests के लिए करें।",
    "Protected Support": "सुरक्षित सपोर्ट",
    "Support remains guidance-only and protection-first.": "Support guidance-only और protection-first रहता है।",
    "Email Routing": "Email routing",
    "Messages go directly to MIT PRO support/admin.": "Messages सीधे MIT PRO support/admin तक जाते हैं।",
    "Clear Context": "स्पष्ट संदर्भ",
    "Include account email, device details, and a short issue summary.": "Account email, device details और short issue summary शामिल करें।",
    "Support Rule": "Support rule",
    "No financial advice": "कोई वित्तीय सलाह नहीं",
    "No guaranteed outcome claims": "Guaranteed outcome claims नहीं",
    "No seed phrase or private key requests": "Seed phrase या private key requests नहीं",
    "Include account email, device details, and what you need help with.": "Account email, device details और आपको किस बात में मदद चाहिए यह शामिल करें।",
    "Secure support request": "सुरक्षित support request",
    "Your message will be sent directly to MIT PRO support.": "आपका message सीधे MIT PRO support को भेजा जाएगा।",
    "You can also email support@mitpro.ai directly.": "आप support@mitpro.ai पर सीधे email भी कर सकते हैं।",
    "Partner Portal": "पार्टनर पोर्टल",
    "Sales": "सेल्स",
    "Workspace": "वर्कस्पेस",
    "Email / Username": "ईमेल / यूज़रनेम",
    "Password": "पासवर्ड",
    "Master": "मास्टर",
    "Sales & business intelligence command": "सेल्स और बिजनेस इंटेलिजेंस कमांड",
    "MIT Pro Master": "MIT Pro मास्टर",
    "Protection mode active": "सुरक्षा मोड सक्रिय",
    "Zeus AI standby": "Zeus AI स्टैंडबाय",
    "Arjun Guard ready": "Arjun Guard तैयार",
    "Owner command center loaded.": "Owner command center loaded.",
    "Signed in": "साइन इन",
    "MIT Pro User": "MIT Pro उपयोगकर्ता",
    "Normal": "सामान्य",
    "Market clarity": "बाजार स्पष्टता",
    "Live": "लाइव",
    "Terminal": "टर्मिनल",
    "Refresh": "रिफ्रेश",
    "AI Protection State": "AI सुरक्षा स्थिति",
    "Market Clarity": "बाजार स्पष्टता",
    "Clear": "स्पष्ट",
    "Volatility low": "अस्थिरता कम",
    "System Health": "सिस्टम स्वास्थ्य",
    "All systems online": "सभी सिस्टम ऑनलाइन",
    "Owner Access": "Owner access",
    "Full control": "पूर्ण नियंत्रण",
    "Confirmed Revenue": "Confirmed revenue",
    "Server data": "Server data",
    "Active Customers": "सक्रिय ग्राहक",
    "Tracked licenses": "Tracked licenses",
    "New Licenses 30D": "नए लाइसेंस 30D",
    "Pending requests": "Pending requests",
    "Renewal Rate": "Renewal rate",
    "Projected health": "Projected health",
    "Avg. Confirmed Deal": "Avg. confirmed deal",
    "From paid records": "Paid records से",
    "Gross Margin": "Gross margin",
    "No cost data loaded": "Cost data loaded नहीं",
    "Zeus AI insight": "Zeus AI insight",
    "AI Owner Brief": "AI owner brief",
    "Strong sales momentum detected.": "Strong sales momentum detected.",
    "Renewal pipeline is healthy and customer follow-up remains clean.": "Renewal pipeline healthy है और customer follow-up clean है।",
    "Focus on renewal follow-up and referral quality.": "Renewal follow-up और referral quality पर ध्यान दें।",
    "Referral program is driving protected customer conversations.": "Referral program protected customer conversations को support कर रहा है।",
    "AI recommendations": "AI recommendations",
    "Actions": "Actions",
    "Alerts & notifications": "Alerts और notifications",
    "Watchlist": "Watchlist",
    "Sales performance": "Sales performance",
    "YTD Trend": "YTD trend",
    "Renewal pipeline": "Renewal pipeline",
    "Pipeline": "Pipeline",
    "Referral performance": "Referral performance",
    "Conversion": "Conversion",
    "License health": "License health",
    "Health": "Health",
    "Top customers": "Top customers",
    "Referral Codes": "Referral codes",
    "Renewals due soon": "Renewals due soon",
    "License Follow-Up": "License follow-up",
    "Justification required": "Justification required",
    "License Action": "License action",
    "Select an action": "Action चुनें",
    "Write the support reason before changing any customer license state. This is saved in license history.": "Customer license state बदलने से पहले support reason लिखें। यह license history में save होगा।",
    "Action Justification": "Action justification",
    "CONFIRM ACTION": "Action confirm करें",
    "CANCEL": "Cancel",
    "Payment confirmation required": "Payment confirmation required",
    "Renew License": "लाइसेंस renew करें",
    "Select a license": "License चुनें",
    "Renewal is limited to 30 days and must include confirmed payment evidence plus support justification.": "Renewal 30 days तक सीमित है और उसमें confirmed payment evidence plus support justification होना चाहिए।",
    "Payment Reference": "Payment reference",
    "Payment Note / Justification": "Payment note / justification",
    "CONFIRM RENEWAL": "Renewal confirm करें",
    "Recent activities": "Recent activities",
    "Referral Activity": "Referral activity",
    "Owner shortcuts": "Owner shortcuts",
    "Quick Access": "Quick access",
    "Arjun warning users": "Arjun warning users",
    "User Protection Watch": "User protection watch",
    "Loading Arjun watchlist...": "Arjun watchlist loading...",
    "Select a user": "User चुनें",
    "No financial advice. Calm support only.": "कोई financial advice नहीं। केवल calm support।",
    "Pause": "Pause",
    "Protect": "Protect",
    "Cooldown": "Cooldown",
    "SEND": "Send",
    "COMPLETE": "Complete",
    "CLEAR": "Clear",
    "Master only": "Master only",
    "Owner Sales Layer": "Owner sales layer",
    "MIT Pro partner network": "MIT Pro partner network",
    "Promote with": "Promote with",
    "protected intelligence": "protected intelligence",
    "Share approved access, support renewals, and keep every customer conversation aligned with MIT Pro's protection-first standard.": "Approved access share करें, renewals support करें, और हर customer conversation को MIT Pro के protection-first standard के साथ aligned रखें।",
    "Apex Prime Core": "Apex Prime Core",
    "AI command center": "AI command center",
    "Browse Intelligence": "Browse intelligence",
    "Loading intelligence categories...": "Intelligence categories loading...",
    "Master command center": "Master command center",
    "MIT Pro Admin Command Center": "MIT Pro admin command center",
    "Loading Master command center...": "Master command center loading...",
    "Strategy intelligence": "Strategy intelligence",
    "Strategy Performance": "Strategy performance",
    "Loading strategy intelligence...": "Strategy intelligence loading...",
    "Result quality": "Result quality",
    "Evidence Quality": "Evidence quality",
    "Loading result quality...": "Result quality loading...",
    "User integrity AI": "User integrity AI",
    "Pattern Review": "Pattern review",
    "Loading integrity intelligence...": "Integrity intelligence loading...",
    "System health": "System health",
    "Server & Cloud Health": "Server और cloud health",
    "Loading system health...": "System health loading...",
    "Reports center": "Reports center",
    "Export & Review Packs": "Export और review packs",
    "Loading report center...": "Report center loading...",
    "Market Stability": "Market stability",
    "Caution": "Caution",
    "Validation State": "Validation state",
    "Wait": "Wait",
    "Market Health": "Market health",
    "Moderate": "Moderate",
    "Arjun State": "Arjun state",
    "Ready": "Ready",
    "Last Sync": "Last sync",
    "System Time": "System time",
    "Example: Customer requested hold after verification call": "Example: Verification call के बाद customer ने hold request किया",
    "Transaction ID / receipt / payment reference": "Transaction ID / receipt / payment reference",
    "Example: Payment verified in bank/Stripe by admin": "Example: Admin ने bank/Stripe में payment verify किया",
    "Calm support message only": "केवल calm support message",
    "MIT PRO is not financial advice and does not guarantee trading results.": "MIT PRO वित्तीय सलाह नहीं है और ट्रेडिंग परिणामों की गारंटी नहीं देता।",
    "© 2026 MIT PRO. All rights reserved.": "© 2026 MIT PRO. सर्वाधिकार सुरक्षित।"
  };

  const originals = new WeakMap();
  const ignoredTags = new Set(["SCRIPT", "STYLE", "NOSCRIPT", "SVG", "PATH", "SYMBOL"]);

  function translateText(text, language) {
    if (language === "en") return text;
    const trimmed = text.trim();
    if (!trimmed) return text;
    const translated = translations[trimmed];
    if (!translated) return text;
    return text.replace(trimmed, translated);
  }

  function applyLanguage(language) {
    document.documentElement.lang = language === "hi" ? "hi" : "en";
    document.body.classList.toggle("lang-hi", language === "hi");

    const walker = document.createTreeWalker(document.body, NodeFilter.SHOW_TEXT, {
      acceptNode(node) {
        const parent = node.parentElement;
        if (!parent || ignoredTags.has(parent.tagName)) return NodeFilter.FILTER_REJECT;
        if (parent.closest(".language-switch")) return NodeFilter.FILTER_REJECT;
        if (!node.textContent.trim()) return NodeFilter.FILTER_REJECT;
        return NodeFilter.FILTER_ACCEPT;
      }
    });

    const nodes = [];
    while (walker.nextNode()) nodes.push(walker.currentNode);
    nodes.forEach((node) => {
      if (!originals.has(node)) originals.set(node, node.textContent);
      node.textContent = translateText(originals.get(node), language);
    });

    document.querySelectorAll("[placeholder]").forEach((field) => {
      if (!field.dataset.originalPlaceholder) field.dataset.originalPlaceholder = field.getAttribute("placeholder") || "";
      field.setAttribute("placeholder", translateText(field.dataset.originalPlaceholder, language));
    });

    document.querySelectorAll("[data-language]").forEach((button) => {
      const active = button.dataset.language === language;
      button.classList.toggle("active", active);
      button.setAttribute("aria-pressed", active ? "true" : "false");
    });
  }

  function initLanguageSwitch() {
    const saved = localStorage.getItem("mitpro-language") || "en";
    document.querySelectorAll("[data-language]").forEach((button) => {
      button.addEventListener("click", () => {
        const language = button.dataset.language === "hi" ? "hi" : "en";
        localStorage.setItem("mitpro-language", language);
        applyLanguage(language);
      });
    });
    applyLanguage(saved === "hi" ? "hi" : "en");
  }

  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", initLanguageSwitch);
  } else {
    initLanguageSwitch();
  }
})();
